-- =============================================================================
-- GYMGO - Seed Global Exercises Library
-- 200+ exercises with GymVisual.com GIFs
-- =============================================================================

-- Note: GIF URLs follow GymVisual.com pattern
-- You may need to verify/update URLs based on their current structure

INSERT INTO exercises (
  organization_id,
  name,
  name_es,
  name_en,
  description,
  category,
  muscle_groups,
  equipment,
  difficulty,
  gif_url,
  instructions,
  tips,
  is_global,
  is_active
) VALUES

-- =============================================================================
-- PECHO / CHEST (20 exercises)
-- =============================================================================

(NULL, 'Press de banca con barra', 'Press de banca con barra', 'Barbell Bench Press',
 'Ejercicio fundamental para desarrollo del pecho',
 'strength', ARRAY['chest', 'triceps', 'shoulders'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/8/5/1785.gif',
 ARRAY['Acuestate en el banco con los pies firmes en el suelo', 'Agarra la barra con las manos ligeramente mas anchas que los hombros', 'Baja la barra controladamente hasta el pecho', 'Empuja hacia arriba hasta extender los brazos'],
 ARRAY['Mantén los omóplatos retraídos', 'No rebotes la barra en el pecho'],
 true, true),

(NULL, 'Press de banca inclinado', 'Press de banca inclinado', 'Incline Bench Press',
 'Enfatiza la porcion superior del pecho',
 'strength', ARRAY['chest', 'shoulders', 'triceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/7/1/2071.gif',
 ARRAY['Ajusta el banco a 30-45 grados', 'Baja la barra hacia la parte superior del pecho', 'Empuja hacia arriba en linea recta'],
 ARRAY['No uses un angulo mayor a 45 grados'],
 true, true),

(NULL, 'Press de banca declinado', 'Press de banca declinado', 'Decline Bench Press',
 'Enfatiza la porcion inferior del pecho',
 'strength', ARRAY['chest', 'triceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/9/3/1793.gif',
 ARRAY['Ajusta el banco en declinacion', 'Asegura los pies en los soportes', 'Baja la barra hacia el pecho inferior'],
 ARRAY['Usa un ayudante para pasar la barra'],
 true, true),

(NULL, 'Press con mancuernas', 'Press con mancuernas', 'Dumbbell Bench Press',
 'Mayor rango de movimiento que con barra',
 'strength', ARRAY['chest', 'triceps', 'shoulders'], ARRAY['dumbbell', 'bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/8/0/5/1805.gif',
 ARRAY['Acuestate con una mancuerna en cada mano', 'Baja las mancuernas a los lados del pecho', 'Empuja hacia arriba juntando las mancuernas'],
 ARRAY['Permite mayor estiramiento en la parte baja'],
 true, true),

(NULL, 'Aperturas con mancuernas', 'Aperturas con mancuernas', 'Dumbbell Flyes',
 'Aislamiento para el pecho',
 'strength', ARRAY['chest'], ARRAY['dumbbell', 'bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/8/1/5/1815.gif',
 ARRAY['Acuestate con mancuernas sobre el pecho', 'Baja los brazos en arco manteniendo codos ligeramente flexionados', 'Regresa apretando el pecho'],
 ARRAY['No bajes demasiado para evitar lesiones'],
 true, true),

(NULL, 'Aperturas en polea', 'Aperturas en polea', 'Cable Crossover',
 'Tension constante durante todo el movimiento',
 'strength', ARRAY['chest'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/8/7/1187.gif',
 ARRAY['Coloca las poleas en posicion alta', 'Da un paso adelante con un pie', 'Junta las manos frente al pecho en arco'],
 ARRAY['Mantén una ligera flexion en los codos'],
 true, true),

(NULL, 'Fondos en paralelas', 'Fondos en paralelas', 'Parallel Bar Dips',
 'Ejercicio compuesto para pecho y triceps',
 'strength', ARRAY['chest', 'triceps', 'shoulders'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/1/4/7/2147.gif',
 ARRAY['Sujétate de las barras paralelas', 'Inclina el torso hacia adelante para enfatizar pecho', 'Baja hasta que los codos formen 90 grados', 'Empuja hacia arriba'],
 ARRAY['Inclina mas el torso para mas pecho'],
 true, true),

(NULL, 'Push-ups', 'Flexiones de pecho', 'Push-ups',
 'Ejercicio clasico de peso corporal',
 'strength', ARRAY['chest', 'triceps', 'shoulders'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/4/1/9/4419.gif',
 ARRAY['Coloca las manos a la anchura de los hombros', 'Mantén el cuerpo en linea recta', 'Baja el pecho hacia el suelo', 'Empuja hacia arriba'],
 ARRAY['No dejes caer las caderas'],
 true, true),

(NULL, 'Push-ups diamante', 'Flexiones diamante', 'Diamond Push-ups',
 'Variacion que enfatiza triceps',
 'strength', ARRAY['chest', 'triceps'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/4/2/3/4423.gif',
 ARRAY['Junta las manos formando un diamante', 'Baja el pecho hacia las manos', 'Empuja hacia arriba'],
 ARRAY['Mantén los codos cerca del cuerpo'],
 true, true),

(NULL, 'Press en maquina', 'Press en maquina', 'Machine Chest Press',
 'Movimiento guiado ideal para principiantes',
 'strength', ARRAY['chest', 'triceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/8/9/1789.gif',
 ARRAY['Ajusta el asiento a la altura correcta', 'Agarra las manijas', 'Empuja hacia adelante', 'Regresa controladamente'],
 ARRAY['No bloquees los codos completamente'],
 true, true),

(NULL, 'Pullover con mancuerna', 'Pullover con mancuerna', 'Dumbbell Pullover',
 'Trabaja pecho y espalda',
 'strength', ARRAY['chest', 'back'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/8/2/5/1825.gif',
 ARRAY['Acuestate perpendicular al banco', 'Sostén una mancuerna sobre el pecho', 'Baja hacia atras manteniendo brazos extendidos', 'Regresa a la posicion inicial'],
 ARRAY['No uses demasiado peso'],
 true, true),

(NULL, 'Press inclinado con mancuernas', 'Press inclinado con mancuernas', 'Incline Dumbbell Press',
 'Desarrollo de pecho superior con mancuernas',
 'strength', ARRAY['chest', 'shoulders', 'triceps'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/7/5/2075.gif',
 ARRAY['Ajusta el banco a 30-45 grados', 'Presiona las mancuernas hacia arriba', 'Baja controladamente'],
 ARRAY['Junta las mancuernas arriba para mayor contraccion'],
 true, true),

(NULL, 'Aperturas inclinadas', 'Aperturas inclinadas', 'Incline Dumbbell Flyes',
 'Aislamiento para pecho superior',
 'strength', ARRAY['chest'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/8/3/2083.gif',
 ARRAY['Banco inclinado a 30-45 grados', 'Abre los brazos en arco', 'Junta las mancuernas arriba'],
 ARRAY['Mantén tension constante'],
 true, true),

(NULL, 'Press con agarre cerrado', 'Press con agarre cerrado', 'Close Grip Bench Press',
 'Enfatiza triceps con trabajo de pecho',
 'strength', ARRAY['triceps', 'chest'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/8/7/1787.gif',
 ARRAY['Agarra la barra con manos separadas 15-20cm', 'Baja la barra al pecho bajo', 'Empuja manteniendo codos cerca del cuerpo'],
 ARRAY['No uses agarre demasiado cerrado'],
 true, true),

(NULL, 'Pec deck', 'Pec deck', 'Pec Deck Machine',
 'Maquina de aislamiento para pecho',
 'strength', ARRAY['chest'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/8/3/1/1831.gif',
 ARRAY['Ajusta el asiento', 'Coloca los antebrazos en las almohadillas', 'Junta los brazos frente al pecho'],
 ARRAY['No uses momentum'],
 true, true),

(NULL, 'Flexiones con pies elevados', 'Flexiones con pies elevados', 'Decline Push-ups',
 'Mayor enfasis en pecho superior',
 'strength', ARRAY['chest', 'shoulders', 'triceps'], ARRAY['bodyweight', 'box'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/4/2/1/4421.gif',
 ARRAY['Coloca los pies en una superficie elevada', 'Realiza flexiones normales', 'Mantén el core apretado'],
 ARRAY['Mayor elevacion = mayor dificultad'],
 true, true),

(NULL, 'Press Svend', 'Press Svend', 'Svend Press',
 'Contraccion isometrica del pecho',
 'strength', ARRAY['chest'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/5/0/1/5/5015.gif',
 ARRAY['Sostén un disco o mancuerna contra el pecho', 'Presiona las palmas juntas', 'Extiende los brazos hacia adelante', 'Regresa al pecho'],
 ARRAY['Mantén tension constante presionando'],
 true, true),

(NULL, 'Cruces en polea baja', 'Cruces en polea baja', 'Low Cable Crossover',
 'Enfatiza pecho superior',
 'strength', ARRAY['chest'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/8/9/1189.gif',
 ARRAY['Poleas en posicion baja', 'Junta las manos arriba frente al pecho', 'Controla el descenso'],
 ARRAY['Aprieta el pecho en la contraccion'],
 true, true),

(NULL, 'Floor press', 'Press en suelo', 'Floor Press',
 'Limita rango de movimiento, enfatiza triceps',
 'strength', ARRAY['chest', 'triceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/6/0/7/5/6075.gif',
 ARRAY['Acuestate en el suelo', 'Baja la barra hasta que los codos toquen el suelo', 'Empuja hacia arriba'],
 ARRAY['Ideal para superar estancamientos'],
 true, true),

(NULL, 'Landmine press', 'Press con barra T', 'Landmine Press',
 'Press unilateral con barra',
 'strength', ARRAY['chest', 'shoulders'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/9/3/5893.gif',
 ARRAY['Coloca un extremo de la barra en una esquina', 'Sostén el otro extremo con ambas manos', 'Presiona hacia arriba y adelante'],
 ARRAY['Mantén el core estable'],
 true, true),

-- =============================================================================
-- ESPALDA / BACK (25 exercises)
-- =============================================================================

(NULL, 'Dominadas', 'Dominadas', 'Pull-ups',
 'Ejercicio fundamental para espalda',
 'strength', ARRAY['back', 'biceps'], ARRAY['pull_up_bar'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/5/5/3/1553.gif',
 ARRAY['Cuelgate de la barra con agarre prono', 'Tira hacia arriba hasta que la barbilla pase la barra', 'Baja controladamente'],
 ARRAY['Retrae los omoplatos al subir'],
 true, true),

(NULL, 'Dominadas con agarre supino', 'Dominadas supinas', 'Chin-ups',
 'Mayor enfasis en biceps',
 'strength', ARRAY['back', 'biceps'], ARRAY['pull_up_bar'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/5/5/1/1551.gif',
 ARRAY['Agarre supino (palmas hacia ti)', 'Tira hasta que la barbilla pase la barra', 'Baja con control'],
 ARRAY['Mas facil que dominadas pronadas'],
 true, true),

(NULL, 'Remo con barra', 'Remo con barra', 'Barbell Row',
 'Ejercicio compuesto para espalda',
 'strength', ARRAY['back', 'biceps', 'lower_back'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/2/6/9/1269.gif',
 ARRAY['Inclinate hacia adelante con la espalda recta', 'Tira de la barra hacia el abdomen', 'Baja controladamente'],
 ARRAY['No uses momentum del torso'],
 true, true),

(NULL, 'Remo con mancuerna', 'Remo con mancuerna', 'Dumbbell Row',
 'Trabajo unilateral de espalda',
 'strength', ARRAY['back', 'biceps'], ARRAY['dumbbell', 'bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/6/1/1661.gif',
 ARRAY['Apoya una mano y rodilla en el banco', 'Tira de la mancuerna hacia la cadera', 'Baja controladamente'],
 ARRAY['Mantén la espalda paralela al suelo'],
 true, true),

(NULL, 'Peso muerto', 'Peso muerto', 'Deadlift',
 'Rey de los ejercicios compuestos',
 'strength', ARRAY['back', 'glutes', 'hamstrings', 'lower_back'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/1/9/8/5/1985.gif',
 ARRAY['Pies a la anchura de caderas', 'Agarra la barra fuera de las piernas', 'Levanta manteniendo la espalda recta', 'Extiende caderas y rodillas simultaneamente'],
 ARRAY['Mantén la barra cerca del cuerpo'],
 true, true),

(NULL, 'Peso muerto rumano', 'Peso muerto rumano', 'Romanian Deadlift',
 'Enfatiza isquiotibiales y gluteos',
 'strength', ARRAY['hamstrings', 'glutes', 'lower_back'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/9/8/9/1989.gif',
 ARRAY['Comienza de pie con la barra', 'Baja empujando las caderas hacia atras', 'Mantén las piernas casi rectas', 'Siente el estiramiento en isquiotibiales'],
 ARRAY['No redondees la espalda'],
 true, true),

(NULL, 'Jalon al pecho', 'Jalon al pecho', 'Lat Pulldown',
 'Version asistida de dominadas',
 'strength', ARRAY['back', 'biceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/2/7/7/1277.gif',
 ARRAY['Sientate y fija las piernas bajo las almohadillas', 'Tira de la barra hacia el pecho', 'Controla el regreso'],
 ARRAY['No te inclines demasiado hacia atras'],
 true, true),

(NULL, 'Jalon tras nuca', 'Jalon tras nuca', 'Behind Neck Pulldown',
 'Variacion con mayor enfasis en dorsales',
 'strength', ARRAY['back'], ARRAY['cable'],
 'advanced',
 'https://www.gymvisual.com/img/p/1/2/7/9/1279.gif',
 ARRAY['Tira de la barra detras de la cabeza', 'Mantén el torso recto', 'Controla el movimiento'],
 ARRAY['Requiere buena movilidad de hombros'],
 true, true),

(NULL, 'Remo en polea baja', 'Remo en polea baja', 'Seated Cable Row',
 'Remo con tension constante',
 'strength', ARRAY['back', 'biceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/6/9/1669.gif',
 ARRAY['Sientate con pies en la plataforma', 'Tira del agarre hacia el abdomen', 'Retrae los omoplatos', 'Regresa controladamente'],
 ARRAY['No uses el impulso del torso'],
 true, true),

(NULL, 'Remo en maquina', 'Remo en maquina', 'Machine Row',
 'Movimiento guiado de remo',
 'strength', ARRAY['back', 'biceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/7/1/1671.gif',
 ARRAY['Ajusta el asiento', 'Tira de las manijas hacia el torso', 'Aprieta los omoplatos'],
 ARRAY['Ideal para principiantes'],
 true, true),

(NULL, 'Remo T-bar', 'Remo T-bar', 'T-Bar Row',
 'Remo con agarre neutro',
 'strength', ARRAY['back', 'biceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/6/6/5/1665.gif',
 ARRAY['Coloca la barra en el soporte T', 'Inclinate y agarra la manija', 'Tira hacia el pecho'],
 ARRAY['Mantén la espalda recta'],
 true, true),

(NULL, 'Face pull', 'Face pull', 'Face Pull',
 'Excelente para deltoides posterior y rotadores',
 'strength', ARRAY['shoulders', 'back'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/9/5/1195.gif',
 ARRAY['Polea a la altura de la cara', 'Tira hacia la cara separando las manos', 'Retrae los omoplatos'],
 ARRAY['Excelente para postura'],
 true, true),

(NULL, 'Pullover en polea', 'Pullover en polea', 'Cable Pullover',
 'Aislamiento para dorsales',
 'strength', ARRAY['back'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/2/0/1/1201.gif',
 ARRAY['Polea en posicion alta', 'Brazos extendidos, tira hacia abajo', 'Mantén los brazos rectos'],
 ARRAY['Siente el estiramiento de los dorsales'],
 true, true),

(NULL, 'Dominadas asistidas', 'Dominadas asistidas', 'Assisted Pull-ups',
 'Version para principiantes',
 'strength', ARRAY['back', 'biceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/5/5/5/1555.gif',
 ARRAY['Selecciona el peso de asistencia', 'Arrodillate en la plataforma', 'Realiza dominadas normales'],
 ARRAY['Reduce la asistencia progresivamente'],
 true, true),

(NULL, 'Rack pull', 'Rack pull', 'Rack Pull',
 'Peso muerto parcial desde soportes',
 'strength', ARRAY['back', 'glutes', 'lower_back'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/9/9/1/1991.gif',
 ARRAY['Coloca la barra en soportes a la altura de rodillas', 'Levanta extendiendo caderas', 'Baja con control'],
 ARRAY['Permite usar mas peso que peso muerto completo'],
 true, true),

(NULL, 'Good morning', 'Buenos dias', 'Good Morning',
 'Fortalece espalda baja e isquiotibiales',
 'strength', ARRAY['lower_back', 'hamstrings', 'glutes'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/8/4/1/4841.gif',
 ARRAY['Barra en la espalda como sentadilla', 'Inclinate hacia adelante desde la cadera', 'Mantén la espalda recta', 'Regresa a la posicion vertical'],
 ARRAY['Empieza con peso ligero'],
 true, true),

(NULL, 'Hiperextensiones', 'Hiperextensiones', 'Back Extensions',
 'Fortalece la cadena posterior',
 'strength', ARRAY['lower_back', 'glutes', 'hamstrings'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/8/1/9/4819.gif',
 ARRAY['Colócate en el banco de hiperextensiones', 'Baja el torso hacia el suelo', 'Sube contrayendo gluteos y espalda baja'],
 ARRAY['No hiperextiendas la espalda'],
 true, true),

(NULL, 'Superman', 'Superman', 'Superman Hold',
 'Ejercicio de peso corporal para espalda baja',
 'strength', ARRAY['lower_back', 'glutes'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/8/2/7/4827.gif',
 ARRAY['Acuestate boca abajo', 'Levanta brazos y piernas simultaneamente', 'Mantén la posicion', 'Baja con control'],
 ARRAY['Aprieta los gluteos al subir'],
 true, true),

(NULL, 'Remo Pendlay', 'Remo Pendlay', 'Pendlay Row',
 'Remo explosivo desde el suelo',
 'strength', ARRAY['back', 'biceps'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/1/2/7/1/1271.gif',
 ARRAY['La barra descansa en el suelo cada rep', 'Torso paralelo al suelo', 'Tira explosivamente hacia el pecho', 'Baja la barra al suelo'],
 ARRAY['Mantén la posicion del torso constante'],
 true, true),

(NULL, 'Remo invertido', 'Remo invertido', 'Inverted Row',
 'Remo de peso corporal',
 'strength', ARRAY['back', 'biceps'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/8/1/1681.gif',
 ARRAY['Cuelgate de una barra baja', 'Tira del pecho hacia la barra', 'Mantén el cuerpo recto'],
 ARRAY['Ajusta la altura para variar dificultad'],
 true, true),

(NULL, 'Encogimientos con barra', 'Encogimientos con barra', 'Barbell Shrugs',
 'Aislamiento para trapecios',
 'strength', ARRAY['back'], ARRAY['barbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/8/3/1683.gif',
 ARRAY['Sostén la barra con brazos extendidos', 'Eleva los hombros hacia las orejas', 'Baja controladamente'],
 ARRAY['No rotes los hombros'],
 true, true),

(NULL, 'Encogimientos con mancuernas', 'Encogimientos con mancuernas', 'Dumbbell Shrugs',
 'Trabajo de trapecios con mancuernas',
 'strength', ARRAY['back'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/8/5/1685.gif',
 ARRAY['Mancuernas a los lados', 'Eleva los hombros', 'Mantén arriba un segundo'],
 ARRAY['Mayor rango de movimiento que con barra'],
 true, true),

(NULL, 'Jalon con agarre cerrado', 'Jalon con agarre cerrado', 'Close Grip Pulldown',
 'Variacion que enfatiza la parte baja de dorsales',
 'strength', ARRAY['back', 'biceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/2/8/1/1281.gif',
 ARRAY['Usa un agarre en V o cerrado', 'Tira hacia el pecho', 'Aprieta los dorsales abajo'],
 ARRAY['Inclinate ligeramente hacia atras'],
 true, true),

(NULL, 'Remo con agarre ancho', 'Remo con agarre ancho', 'Wide Grip Row',
 'Mayor enfasis en dorsales externos',
 'strength', ARRAY['back'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/6/7/5/1675.gif',
 ARRAY['Usa una barra ancha en polea baja', 'Tira hacia el pecho alto', 'Retrae los omoplatos'],
 ARRAY['Codos hacia afuera'],
 true, true),

(NULL, 'Deficit deadlift', 'Peso muerto con deficit', 'Deficit Deadlift',
 'Mayor rango de movimiento en peso muerto',
 'strength', ARRAY['back', 'glutes', 'hamstrings'], ARRAY['barbell', 'box'],
 'advanced',
 'https://www.gymvisual.com/img/p/1/9/8/7/1987.gif',
 ARRAY['Parate sobre una plataforma de 2-4 pulgadas', 'Realiza peso muerto normal', 'Mayor flexion de rodillas'],
 ARRAY['Reduce el peso comparado con peso muerto normal'],
 true, true),

-- =============================================================================
-- HOMBROS / SHOULDERS (20 exercises)
-- =============================================================================

(NULL, 'Press militar', 'Press militar', 'Overhead Press',
 'Ejercicio fundamental para hombros',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/1/3/2313.gif',
 ARRAY['Barra a la altura de los hombros', 'Presiona hacia arriba sobre la cabeza', 'Bloquea los codos arriba', 'Baja controladamente'],
 ARRAY['Aprieta los gluteos para estabilidad'],
 true, true),

(NULL, 'Press Arnold', 'Press Arnold', 'Arnold Press',
 'Variacion que trabaja todos los angulos del deltoides',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/2/1/2321.gif',
 ARRAY['Comienza con mancuernas frente al pecho, palmas hacia ti', 'Rota mientras presionas hacia arriba', 'Termina con palmas hacia adelante'],
 ARRAY['Movimiento fluido de rotacion'],
 true, true),

(NULL, 'Press con mancuernas sentado', 'Press con mancuernas sentado', 'Seated Dumbbell Press',
 'Press de hombros con soporte de espalda',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['dumbbell', 'bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/1/9/2319.gif',
 ARRAY['Sientate con espalda apoyada', 'Mancuernas a la altura de los hombros', 'Presiona hacia arriba'],
 ARRAY['No arquees la espalda'],
 true, true),

(NULL, 'Elevaciones laterales', 'Elevaciones laterales', 'Lateral Raises',
 'Aislamiento para deltoides lateral',
 'strength', ARRAY['shoulders'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/3/1/2331.gif',
 ARRAY['Mancuernas a los lados', 'Eleva los brazos hasta la altura de hombros', 'Mantén ligera flexion en codos', 'Baja controladamente'],
 ARRAY['No balancees el cuerpo'],
 true, true),

(NULL, 'Elevaciones frontales', 'Elevaciones frontales', 'Front Raises',
 'Aislamiento para deltoides anterior',
 'strength', ARRAY['shoulders'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/4/1/2341.gif',
 ARRAY['Mancuernas frente a los muslos', 'Eleva un brazo a la vez hasta la altura del hombro', 'Alterna brazos'],
 ARRAY['Controla el descenso'],
 true, true),

(NULL, 'Pajaros', 'Pajaros', 'Reverse Flyes',
 'Aislamiento para deltoides posterior',
 'strength', ARRAY['shoulders', 'back'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/5/1/2351.gif',
 ARRAY['Inclinate hacia adelante', 'Levanta las mancuernas hacia los lados', 'Aprieta los omoplatos'],
 ARRAY['Mantén los codos ligeramente flexionados'],
 true, true),

(NULL, 'Remo al menton', 'Remo al menton', 'Upright Row',
 'Trabajo de trapecios y deltoides',
 'strength', ARRAY['shoulders', 'back'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/5/5/2355.gif',
 ARRAY['Barra con agarre cerrado', 'Tira hacia arriba hasta el menton', 'Codos apuntando hacia arriba'],
 ARRAY['Cuidado si tienes problemas de hombro'],
 true, true),

(NULL, 'Press tras nuca', 'Press tras nuca', 'Behind Neck Press',
 'Variacion avanzada de press',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/3/1/5/2315.gif',
 ARRAY['Barra detras de la cabeza', 'Presiona hacia arriba', 'Baja hasta la nuca'],
 ARRAY['Requiere excelente movilidad'],
 true, true),

(NULL, 'Elevaciones laterales en polea', 'Elevaciones laterales en polea', 'Cable Lateral Raises',
 'Tension constante en el deltoides lateral',
 'strength', ARRAY['shoulders'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/3/3/2333.gif',
 ARRAY['Polea en posicion baja', 'Cruza el cable por detras', 'Eleva el brazo lateralmente'],
 ARRAY['Mayor tension al final del movimiento'],
 true, true),

(NULL, 'Press en maquina de hombros', 'Press en maquina de hombros', 'Shoulder Press Machine',
 'Movimiento guiado de press',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/2/5/2325.gif',
 ARRAY['Ajusta el asiento', 'Agarra las manijas', 'Presiona hacia arriba'],
 ARRAY['Ideal para principiantes'],
 true, true),

(NULL, 'Pajaros en maquina', 'Pajaros en maquina', 'Reverse Pec Deck',
 'Aislamiento posterior en maquina',
 'strength', ARRAY['shoulders', 'back'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/3/5/3/2353.gif',
 ARRAY['Sientate mirando hacia la maquina', 'Abre los brazos hacia atras', 'Aprieta los omoplatos'],
 ARRAY['No uses momentum'],
 true, true),

(NULL, 'Push press', 'Push press', 'Push Press',
 'Press con impulso de piernas',
 'strength', ARRAY['shoulders', 'triceps', 'quadriceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/1/7/2317.gif',
 ARRAY['Barra en los hombros', 'Flexiona ligeramente las rodillas', 'Extiende explosivamente y presiona'],
 ARRAY['Permite usar mas peso que press estricto'],
 true, true),

(NULL, 'Landmine lateral raise', 'Elevacion lateral con barra T', 'Landmine Lateral Raise',
 'Variacion unica de elevacion lateral',
 'strength', ARRAY['shoulders'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/9/5/5895.gif',
 ARRAY['Extremo de barra en esquina', 'Sostén el otro extremo con una mano', 'Eleva lateralmente'],
 ARRAY['Diferente curva de resistencia'],
 true, true),

(NULL, 'Elevacion lateral inclinado', 'Elevacion lateral inclinado', 'Incline Lateral Raise',
 'Mayor rango de movimiento',
 'strength', ARRAY['shoulders'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/3/3/5/2335.gif',
 ARRAY['Acuestate de lado en banco inclinado', 'Eleva la mancuerna lateralmente', 'Controla el descenso'],
 ARRAY['Elimina el impulso del cuerpo'],
 true, true),

(NULL, 'Lu raises', 'Lu raises', 'Lu Raises',
 'Ejercicio híbrido frontal-lateral',
 'strength', ARRAY['shoulders'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/7/7/5877.gif',
 ARRAY['Comienza con mancuernas a los lados', 'Eleva en angulo de 45 grados', 'Hasta la altura de los ojos'],
 ARRAY['Pulgar apuntando hacia arriba'],
 true, true),

(NULL, 'Bradford press', 'Bradford press', 'Bradford Press',
 'Alternancia frente/atras sin bloqueo',
 'strength', ARRAY['shoulders'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/5/8/8/9/5889.gif',
 ARRAY['Barra sobre la cabeza', 'Baja al frente hasta los hombros', 'Sube y baja atras de la cabeza', 'Sin bloquear arriba'],
 ARRAY['Mantén tension constante'],
 true, true),

(NULL, 'Handstand push-ups', 'Flexiones en parada de manos', 'Handstand Push-ups',
 'Ejercicio avanzado de peso corporal',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/4/4/1/4441.gif',
 ARRAY['Parada de manos contra la pared', 'Baja la cabeza hacia el suelo', 'Empuja hacia arriba'],
 ARRAY['Comienza con version asistida'],
 true, true),

(NULL, 'Y raises', 'Elevaciones en Y', 'Y Raises',
 'Fortalece los rotadores y deltoides',
 'strength', ARRAY['shoulders', 'back'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/5/8/7/9/5879.gif',
 ARRAY['Inclinate hacia adelante o acuestate boca abajo', 'Eleva los brazos en forma de Y', 'Pulgares hacia arriba'],
 ARRAY['Usa peso ligero'],
 true, true),

(NULL, 'W raises', 'Elevaciones en W', 'W Raises',
 'Fortalece el manguito rotador',
 'strength', ARRAY['shoulders', 'back'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/5/8/8/1/5881.gif',
 ARRAY['Boca abajo o inclinado', 'Codos a 90 grados', 'Rota externamente formando W'],
 ARRAY['Excelente para rehabilitacion'],
 true, true),

(NULL, 'Cuban press', 'Cuban press', 'Cuban Press',
 'Ejercicio completo para hombros',
 'strength', ARRAY['shoulders'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/8/5/5885.gif',
 ARRAY['Remo vertical hasta codos a 90', 'Rota externamente', 'Presiona hacia arriba', 'Invierte el movimiento'],
 ARRAY['Usa peso muy ligero'],
 true, true),

-- =============================================================================
-- BICEPS (15 exercises)
-- =============================================================================

(NULL, 'Curl con barra', 'Curl con barra', 'Barbell Curl',
 'Ejercicio basico para biceps',
 'strength', ARRAY['biceps'], ARRAY['barbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/3/3/1133.gif',
 ARRAY['De pie con barra, brazos extendidos', 'Flexiona los codos llevando la barra al pecho', 'Baja controladamente'],
 ARRAY['No balancees el cuerpo'],
 true, true),

(NULL, 'Curl con mancuernas', 'Curl con mancuernas', 'Dumbbell Curl',
 'Permite rotacion natural del antebrazo',
 'strength', ARRAY['biceps'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/3/5/1135.gif',
 ARRAY['Mancuernas a los lados', 'Curl alternado o simultaneo', 'Rota el antebrazo durante el movimiento'],
 ARRAY['Supina al final del curl'],
 true, true),

(NULL, 'Curl martillo', 'Curl martillo', 'Hammer Curl',
 'Trabaja biceps y braquial',
 'strength', ARRAY['biceps', 'forearms'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/3/7/1137.gif',
 ARRAY['Agarre neutro (palmas enfrentadas)', 'Curl sin rotar', 'Mantén el agarre neutro'],
 ARRAY['Excelente para el braquial'],
 true, true),

(NULL, 'Curl concentrado', 'Curl concentrado', 'Concentration Curl',
 'Aislamiento maximo de biceps',
 'strength', ARRAY['biceps'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/4/9/1149.gif',
 ARRAY['Sentado, codo apoyado en muslo interno', 'Curl con una mancuerna', 'Aprieta el biceps arriba'],
 ARRAY['No uses impulso'],
 true, true),

(NULL, 'Curl predicador', 'Curl predicador', 'Preacher Curl',
 'Elimina el impulso del cuerpo',
 'strength', ARRAY['biceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/4/1/1141.gif',
 ARRAY['Brazos apoyados en banco predicador', 'Curl con barra o mancuernas', 'Control total del movimiento'],
 ARRAY['No extiendas completamente abajo'],
 true, true),

(NULL, 'Curl en polea', 'Curl en polea', 'Cable Curl',
 'Tension constante durante todo el movimiento',
 'strength', ARRAY['biceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/5/3/1153.gif',
 ARRAY['Polea baja con barra o cuerda', 'Curl manteniendo codos fijos', 'Controla el negativo'],
 ARRAY['No dejes que el peso jale rapido'],
 true, true),

(NULL, 'Curl inclinado', 'Curl inclinado', 'Incline Dumbbell Curl',
 'Mayor estiramiento del biceps',
 'strength', ARRAY['biceps'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/4/3/1143.gif',
 ARRAY['Acostado en banco inclinado', 'Brazos colgando', 'Curl desde la posicion estirada'],
 ARRAY['Excelente para la cabeza larga'],
 true, true),

(NULL, 'Curl 21s', 'Curl 21s', '21s Curl',
 'Tecnica de intensidad para biceps',
 'strength', ARRAY['biceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/3/9/1139.gif',
 ARRAY['7 reps mitad inferior', '7 reps mitad superior', '7 reps rango completo'],
 ARRAY['Usa peso moderado'],
 true, true),

(NULL, 'Curl Scott', 'Curl Scott', 'Scott Curl',
 'Variacion del curl predicador',
 'strength', ARRAY['biceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/4/5/1145.gif',
 ARRAY['Similar al curl predicador', 'Banco mas vertical', 'Mayor aislamiento'],
 ARRAY['Control en la fase negativa'],
 true, true),

(NULL, 'Curl araña', 'Curl araña', 'Spider Curl',
 'Pico de contraccion intenso',
 'strength', ARRAY['biceps'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/4/7/1147.gif',
 ARRAY['Acostado boca abajo en banco inclinado', 'Brazos colgando verticales', 'Curl hacia los hombros'],
 ARRAY['Excelente pico de contraccion'],
 true, true),

(NULL, 'Curl con cuerda', 'Curl con cuerda', 'Rope Curl',
 'Permite rotacion externa al final',
 'strength', ARRAY['biceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/5/5/1155.gif',
 ARRAY['Cuerda en polea baja', 'Curl separando los extremos arriba', 'Aprieta el biceps'],
 ARRAY['Rota las muñecas afuera arriba'],
 true, true),

(NULL, 'Curl Zottman', 'Curl Zottman', 'Zottman Curl',
 'Trabaja biceps y antebrazos',
 'strength', ARRAY['biceps', 'forearms'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/6/1/1161.gif',
 ARRAY['Curl normal subiendo', 'Rota a agarre prono arriba', 'Baja con agarre prono', 'Rota abajo a supino'],
 ARRAY['Combina curl y curl inverso'],
 true, true),

(NULL, 'Curl inverso', 'Curl inverso', 'Reverse Curl',
 'Enfatiza braquial y antebrazos',
 'strength', ARRAY['biceps', 'forearms'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/5/9/1159.gif',
 ARRAY['Agarre prono (palmas hacia abajo)', 'Curl manteniendo el agarre', 'Control en el negativo'],
 ARRAY['Fortalece los antebrazos'],
 true, true),

(NULL, 'Curl en polea alta', 'Curl en polea alta', 'Overhead Cable Curl',
 'Posicion de doble biceps',
 'strength', ARRAY['biceps'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/5/7/1157.gif',
 ARRAY['Poleas altas a cada lado', 'Posicion de doble biceps', 'Curl hacia las orejas'],
 ARRAY['Excelente para el pico del biceps'],
 true, true),

(NULL, 'Drag curl', 'Drag curl', 'Drag Curl',
 'Curl deslizando la barra por el cuerpo',
 'strength', ARRAY['biceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/5/1/5851.gif',
 ARRAY['Barra pegada al cuerpo', 'Codos van hacia atras', 'Desliza la barra subiendo'],
 ARRAY['Enfatiza la cabeza larga'],
 true, true),

-- =============================================================================
-- TRICEPS (15 exercises)
-- =============================================================================

(NULL, 'Extension de triceps en polea', 'Extension de triceps en polea', 'Tricep Pushdown',
 'Ejercicio basico para triceps',
 'strength', ARRAY['triceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/0/3/1703.gif',
 ARRAY['Polea alta con barra o cuerda', 'Codos pegados al cuerpo', 'Extiende los brazos hacia abajo', 'Aprieta el triceps'],
 ARRAY['No muevas los codos'],
 true, true),

(NULL, 'Extension con cuerda', 'Extension con cuerda', 'Rope Pushdown',
 'Permite separar al final para mayor contraccion',
 'strength', ARRAY['triceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/0/5/1705.gif',
 ARRAY['Cuerda en polea alta', 'Extiende y separa los extremos abajo', 'Aprieta el triceps'],
 ARRAY['Separa bien abajo'],
 true, true),

(NULL, 'Fondos en banco', 'Fondos en banco', 'Bench Dips',
 'Ejercicio de peso corporal para triceps',
 'strength', ARRAY['triceps', 'chest'], ARRAY['bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/1/1/1711.gif',
 ARRAY['Manos en el banco detras de ti', 'Baja flexionando los codos', 'Empuja hacia arriba'],
 ARRAY['No bajes demasiado'],
 true, true),

(NULL, 'Press frances', 'Press frances', 'Skull Crusher',
 'Extension de triceps acostado',
 'strength', ARRAY['triceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/2/1/1721.gif',
 ARRAY['Acostado con barra sobre el pecho', 'Baja la barra hacia la frente', 'Extiende los brazos'],
 ARRAY['Controla el peso'],
 true, true),

(NULL, 'Extension sobre cabeza', 'Extension sobre cabeza', 'Overhead Tricep Extension',
 'Estira la cabeza larga del triceps',
 'strength', ARRAY['triceps'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/1/3/1713.gif',
 ARRAY['Mancuerna sobre la cabeza con ambas manos', 'Baja detras de la cabeza', 'Extiende hacia arriba'],
 ARRAY['Mantén los codos apuntando adelante'],
 true, true),

(NULL, 'Patada de triceps', 'Patada de triceps', 'Tricep Kickback',
 'Aislamiento del triceps',
 'strength', ARRAY['triceps'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/1/7/1717.gif',
 ARRAY['Inclinado con brazo paralelo al suelo', 'Extiende el antebrazo hacia atras', 'Aprieta el triceps'],
 ARRAY['No balancees el brazo'],
 true, true),

(NULL, 'Extension en polea sobre cabeza', 'Extension en polea sobre cabeza', 'Overhead Cable Extension',
 'Tension constante en extension sobre cabeza',
 'strength', ARRAY['triceps'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/0/7/1707.gif',
 ARRAY['De espaldas a polea baja', 'Cuerda sobre la cabeza', 'Extiende hacia adelante'],
 ARRAY['Excelente estiramiento'],
 true, true),

(NULL, 'JM Press', 'JM Press', 'JM Press',
 'Hibrido entre press cerrado y extension',
 'strength', ARRAY['triceps', 'chest'], ARRAY['barbell', 'bench'],
 'advanced',
 'https://www.gymvisual.com/img/p/5/8/4/7/5847.gif',
 ARRAY['Acostado como press cerrado', 'Baja la barra hacia el cuello/menton', 'Combinacion de press y extension'],
 ARRAY['Excelente para fuerza de triceps'],
 true, true),

(NULL, 'Extension con mancuerna acostado', 'Extension con mancuerna acostado', 'Lying Dumbbell Extension',
 'Version unilateral del press frances',
 'strength', ARRAY['triceps'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/2/3/1723.gif',
 ARRAY['Acostado con mancuerna en una mano', 'Baja hacia el hombro opuesto', 'Extiende hacia arriba'],
 ARRAY['Controla el peso'],
 true, true),

(NULL, 'Press cerrado en maquina Smith', 'Press cerrado en Smith', 'Smith Machine Close Grip Press',
 'Version guiada del press cerrado',
 'strength', ARRAY['triceps', 'chest'], ARRAY['machine', 'bench'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/8/3/1783.gif',
 ARRAY['Agarre cerrado en maquina Smith', 'Baja al pecho', 'Empuja hacia arriba'],
 ARRAY['Bueno para principiantes'],
 true, true),

(NULL, 'Extension de triceps en maquina', 'Extension de triceps en maquina', 'Tricep Extension Machine',
 'Movimiento guiado de extension',
 'strength', ARRAY['triceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/2/5/1725.gif',
 ARRAY['Ajusta el asiento', 'Coloca los brazos en las almohadillas', 'Extiende hacia abajo'],
 ARRAY['Aislamiento seguro'],
 true, true),

(NULL, 'Diamond push-ups', 'Flexiones diamante', 'Diamond Push-ups',
 'Flexiones con enfasis en triceps',
 'strength', ARRAY['triceps', 'chest'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/4/2/3/4423.gif',
 ARRAY['Manos juntas formando diamante', 'Baja el pecho hacia las manos', 'Empuja hacia arriba'],
 ARRAY['Codos cerca del cuerpo'],
 true, true),

(NULL, 'Extension con barra EZ', 'Extension con barra EZ', 'EZ Bar Skull Crusher',
 'Mas comodo para las muñecas',
 'strength', ARRAY['triceps'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/7/1/9/1719.gif',
 ARRAY['Barra EZ acostado', 'Baja hacia la frente', 'Extiende los brazos'],
 ARRAY['Agarre angulado reduce estres'],
 true, true),

(NULL, 'Press Tate', 'Press Tate', 'Tate Press',
 'Extension horizontal de triceps',
 'strength', ARRAY['triceps'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/4/9/5849.gif',
 ARRAY['Acostado con mancuernas sobre el pecho', 'Baja los pesos hacia el centro del pecho', 'Extiende hacia arriba'],
 ARRAY['Codos apuntan hacia afuera'],
 true, true),

(NULL, 'Extension unilateral en polea', 'Extension unilateral en polea', 'Single Arm Pushdown',
 'Trabajo unilateral de triceps',
 'strength', ARRAY['triceps'], ARRAY['cable'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/7/0/9/1709.gif',
 ARRAY['Manija en polea alta', 'Un brazo a la vez', 'Extiende completamente'],
 ARRAY['Corrige desbalances'],
 true, true),

-- =============================================================================
-- PIERNAS / LEGS (30 exercises)
-- =============================================================================

(NULL, 'Sentadilla con barra', 'Sentadilla con barra', 'Barbell Back Squat',
 'Rey de los ejercicios de piernas',
 'strength', ARRAY['quadriceps', 'glutes', 'hamstrings'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/5/3/2453.gif',
 ARRAY['Barra en la espalda alta', 'Pies a la anchura de hombros', 'Baja hasta que muslos esten paralelos', 'Empuja a través de los talones'],
 ARRAY['Mantén la espalda recta'],
 true, true),

(NULL, 'Sentadilla frontal', 'Sentadilla frontal', 'Front Squat',
 'Mayor enfasis en cuadriceps',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/5/5/2455.gif',
 ARRAY['Barra en la parte frontal de los hombros', 'Codos altos', 'Baja manteniendo el torso vertical'],
 ARRAY['Requiere buena movilidad de muñecas'],
 true, true),

(NULL, 'Prensa de piernas', 'Prensa de piernas', 'Leg Press',
 'Trabajo de piernas con soporte de espalda',
 'strength', ARRAY['quadriceps', 'glutes', 'hamstrings'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/6/3/2463.gif',
 ARRAY['Espalda bien apoyada', 'Pies a la anchura de hombros', 'Baja hasta 90 grados', 'Empuja sin bloquear rodillas'],
 ARRAY['No despegues la espalda baja'],
 true, true),

(NULL, 'Hack squat', 'Hack squat', 'Hack Squat',
 'Sentadilla guiada en maquina',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['machine'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/6/5/2465.gif',
 ARRAY['Hombros en las almohadillas', 'Pies adelantados', 'Baja controladamente', 'Empuja hacia arriba'],
 ARRAY['Menor estres en espalda baja'],
 true, true),

(NULL, 'Extension de piernas', 'Extension de piernas', 'Leg Extension',
 'Aislamiento de cuadriceps',
 'strength', ARRAY['quadriceps'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/6/7/2467.gif',
 ARRAY['Ajusta el respaldo', 'Almohadilla sobre los tobillos', 'Extiende las piernas', 'Aprieta los cuadriceps arriba'],
 ARRAY['No uses impulso'],
 true, true),

(NULL, 'Curl de piernas acostado', 'Curl de piernas acostado', 'Lying Leg Curl',
 'Aislamiento de isquiotibiales',
 'strength', ARRAY['hamstrings'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/2/3/2523.gif',
 ARRAY['Acostado boca abajo', 'Almohadilla sobre los talones', 'Flexiona las piernas', 'Aprieta los isquiotibiales'],
 ARRAY['No levantes las caderas'],
 true, true),

(NULL, 'Curl de piernas sentado', 'Curl de piernas sentado', 'Seated Leg Curl',
 'Variacion sentada del curl',
 'strength', ARRAY['hamstrings'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/2/5/2525.gif',
 ARRAY['Sentado con muslos asegurados', 'Flexiona las piernas hacia atras', 'Control en la extension'],
 ARRAY['Ajusta bien la maquina'],
 true, true),

(NULL, 'Zancadas', 'Zancadas', 'Lunges',
 'Ejercicio unilateral completo',
 'strength', ARRAY['quadriceps', 'glutes', 'hamstrings'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/8/9/2489.gif',
 ARRAY['Da un paso adelante largo', 'Baja la rodilla trasera hacia el suelo', 'Empuja hacia atras', 'Alterna piernas'],
 ARRAY['Rodilla no pase la punta del pie'],
 true, true),

(NULL, 'Zancadas con mancuernas', 'Zancadas con mancuernas', 'Dumbbell Lunges',
 'Zancadas con peso añadido',
 'strength', ARRAY['quadriceps', 'glutes', 'hamstrings'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/9/1/2491.gif',
 ARRAY['Mancuernas a los lados', 'Paso adelante', 'Baja y empuja'],
 ARRAY['Mantén el torso erguido'],
 true, true),

(NULL, 'Zancadas caminando', 'Zancadas caminando', 'Walking Lunges',
 'Version dinamica de zancadas',
 'strength', ARRAY['quadriceps', 'glutes', 'hamstrings'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/9/3/2493.gif',
 ARRAY['Avanza con cada zancada', 'Mantén el ritmo constante', 'Alterna piernas avanzando'],
 ARRAY['Excelente para resistencia'],
 true, true),

(NULL, 'Step-ups', 'Step-ups', 'Step-ups',
 'Subidas a banco o caja',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['box', 'dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/9/9/2499.gif',
 ARRAY['Un pie en la caja', 'Sube empujando con la pierna de arriba', 'Baja controladamente', 'Alterna o haz todas las reps de un lado'],
 ARRAY['No te impulses con la pierna de abajo'],
 true, true),

(NULL, 'Sentadilla bulgara', 'Sentadilla bulgara', 'Bulgarian Split Squat',
 'Sentadilla unilateral avanzada',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['dumbbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/8/5/2485.gif',
 ARRAY['Pie trasero en banco', 'Baja la rodilla hacia el suelo', 'Empuja con la pierna delantera'],
 ARRAY['Excelente para equilibrio muscular'],
 true, true),

(NULL, 'Sentadilla goblet', 'Sentadilla goblet', 'Goblet Squat',
 'Sentadilla con peso frontal',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['dumbbell', 'kettlebell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/5/7/2457.gif',
 ARRAY['Sostén pesa frente al pecho', 'Baja en sentadilla profunda', 'Codos entre las rodillas'],
 ARRAY['Ideal para aprender la sentadilla'],
 true, true),

(NULL, 'Sentadilla sumo', 'Sentadilla sumo', 'Sumo Squat',
 'Enfatiza aductores y gluteos',
 'strength', ARRAY['quadriceps', 'glutes', 'hip_flexors'], ARRAY['dumbbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/5/9/2459.gif',
 ARRAY['Pies muy separados, puntas hacia afuera', 'Baja manteniendo rodillas hacia afuera', 'Empuja hacia arriba'],
 ARRAY['Trabaja bien los aductores'],
 true, true),

(NULL, 'Peso muerto sumo', 'Peso muerto sumo', 'Sumo Deadlift',
 'Variacion de peso muerto con postura ancha',
 'strength', ARRAY['glutes', 'hamstrings', 'quadriceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/9/9/3/1993.gif',
 ARRAY['Postura ancha, agarre dentro de las piernas', 'Espalda recta', 'Extiende caderas y rodillas'],
 ARRAY['Puede ser mas comodo para algunos'],
 true, true),

(NULL, 'Hip thrust', 'Hip thrust', 'Hip Thrust',
 'El mejor ejercicio para gluteos',
 'strength', ARRAY['glutes', 'hamstrings'], ARRAY['barbell', 'bench'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/5/1/5/2515.gif',
 ARRAY['Espalda alta apoyada en banco', 'Barra sobre las caderas', 'Empuja las caderas hacia arriba', 'Aprieta los gluteos arriba'],
 ARRAY['Menton hacia el pecho'],
 true, true),

(NULL, 'Puente de gluteos', 'Puente de gluteos', 'Glute Bridge',
 'Version en suelo del hip thrust',
 'strength', ARRAY['glutes', 'hamstrings'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/1/7/2517.gif',
 ARRAY['Acostado boca arriba', 'Pies apoyados, rodillas flexionadas', 'Eleva las caderas', 'Aprieta los gluteos'],
 ARRAY['Mantén la posicion arriba'],
 true, true),

(NULL, 'Elevaciones de cadera', 'Elevaciones de cadera', 'Hip Raise',
 'Trabajo de gluteos e isquiotibiales',
 'strength', ARRAY['glutes', 'hamstrings'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/1/9/2519.gif',
 ARRAY['Similar al puente pero una pierna', 'Eleva una pierna extendida', 'Empuja con la pierna apoyada'],
 ARRAY['Desafio unilateral'],
 true, true),

(NULL, 'Abduccion de cadera', 'Abduccion de cadera', 'Hip Abduction Machine',
 'Trabajo de gluteo medio',
 'strength', ARRAY['glutes'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/0/7/2507.gif',
 ARRAY['Sentado en la maquina', 'Abre las piernas contra la resistencia', 'Controla el cierre'],
 ARRAY['No uses demasiado peso'],
 true, true),

(NULL, 'Aduccion de cadera', 'Aduccion de cadera', 'Hip Adduction Machine',
 'Trabajo de aductores',
 'strength', ARRAY['hip_flexors'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/0/9/2509.gif',
 ARRAY['Sentado en la maquina', 'Cierra las piernas contra resistencia', 'Control en la apertura'],
 ARRAY['Complementa la abduccion'],
 true, true),

(NULL, 'Elevacion de talones de pie', 'Elevacion de talones de pie', 'Standing Calf Raise',
 'Ejercicio basico para pantorrillas',
 'strength', ARRAY['calves'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/3/1/2531.gif',
 ARRAY['De pie en la maquina', 'Eleva los talones lo mas alto posible', 'Baja estirando bien'],
 ARRAY['Rango completo de movimiento'],
 true, true),

(NULL, 'Elevacion de talones sentado', 'Elevacion de talones sentado', 'Seated Calf Raise',
 'Enfatiza el soleo',
 'strength', ARRAY['calves'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/3/3/2533.gif',
 ARRAY['Sentado con rodillas bajo almohadillas', 'Eleva los talones', 'Baja lentamente'],
 ARRAY['Complementa elevaciones de pie'],
 true, true),

(NULL, 'Prensa de pantorrillas', 'Prensa de pantorrillas', 'Leg Press Calf Raise',
 'Pantorrillas en prensa de piernas',
 'strength', ARRAY['calves'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/5/3/5/2535.gif',
 ARRAY['Solo puntas de pies en la plataforma', 'Empuja con los dedos', 'Baja los talones'],
 ARRAY['Permite usar bastante peso'],
 true, true),

(NULL, 'Sentadilla pistola', 'Sentadilla pistola', 'Pistol Squat',
 'Sentadilla unilateral avanzada',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/4/6/1/2461.gif',
 ARRAY['Una pierna extendida al frente', 'Baja en una pierna hasta abajo', 'Sube sin apoyo'],
 ARRAY['Requiere fuerza y equilibrio'],
 true, true),

(NULL, 'Sissy squat', 'Sissy squat', 'Sissy Squat',
 'Aislamiento extremo de cuadriceps',
 'strength', ARRAY['quadriceps'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/4/8/1/2481.gif',
 ARRAY['De pie, inclinate hacia atras', 'Rodillas van hacia adelante', 'Baja el torso hacia atras'],
 ARRAY['Usa soporte al principio'],
 true, true),

(NULL, 'Curl nordico', 'Curl nordico', 'Nordic Hamstring Curl',
 'Ejercicio excentrico para isquiotibiales',
 'strength', ARRAY['hamstrings'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/5/2/7/2527.gif',
 ARRAY['Arrodillado, pies asegurados', 'Baja el torso lentamente hacia el suelo', 'Empuja para volver o usa las manos'],
 ARRAY['Excelente para prevencion de lesiones'],
 true, true),

(NULL, 'Peso muerto con piernas rigidas', 'Peso muerto con piernas rigidas', 'Stiff Leg Deadlift',
 'Mayor enfasis en isquiotibiales',
 'strength', ARRAY['hamstrings', 'glutes', 'lower_back'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/9/9/5/1995.gif',
 ARRAY['Piernas casi rectas', 'Baja la barra deslizando por las piernas', 'Siente el estiramiento en isquiotibiales'],
 ARRAY['No redondees la espalda'],
 true, true),

(NULL, 'Sentadilla Jefferson', 'Sentadilla Jefferson', 'Jefferson Squat',
 'Variacion asimetrica de sentadilla',
 'strength', ARRAY['quadriceps', 'glutes', 'hip_flexors'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/6/1/5861.gif',
 ARRAY['Barra entre las piernas', 'Un pie adelante, otro atras', 'Baja y sube', 'Alterna posicion'],
 ARRAY['Trabaja estabilizadores'],
 true, true),

(NULL, 'Caminata de granjero', 'Caminata de granjero', 'Farmer Walk',
 'Ejercicio funcional completo',
 'functional', ARRAY['forearms', 'back', 'quadriceps'], ARRAY['dumbbell', 'kettlebell'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/7/9/7/4797.gif',
 ARRAY['Peso pesado en cada mano', 'Camina manteniendo postura erguida', 'Pasos cortos y controlados'],
 ARRAY['Excelente para agarre y core'],
 true, true),

(NULL, 'Reverse lunge', 'Zancada reversa', 'Reverse Lunge',
 'Zancada hacia atras',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/9/5/2495.gif',
 ARRAY['Da un paso hacia atras', 'Baja la rodilla al suelo', 'Regresa a la posicion inicial'],
 ARRAY['Menos estres en rodillas que zancada frontal'],
 true, true),

-- =============================================================================
-- CORE / ABDOMINALES (20 exercises)
-- =============================================================================

(NULL, 'Crunch', 'Crunch abdominal', 'Crunch',
 'Ejercicio basico de abdominales',
 'core', ARRAY['abs'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/1/1/4311.gif',
 ARRAY['Acostado boca arriba, rodillas flexionadas', 'Manos detras de la cabeza', 'Eleva los hombros del suelo', 'Aprieta los abdominales'],
 ARRAY['No tires del cuello'],
 true, true),

(NULL, 'Plancha', 'Plancha', 'Plank',
 'Ejercicio isometrico de core',
 'core', ARRAY['abs', 'obliques', 'lower_back'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/7/1/4371.gif',
 ARRAY['Antebrazos y puntas de pies en el suelo', 'Cuerpo en linea recta', 'Mantén la posicion', 'Aprieta el core'],
 ARRAY['No dejes caer las caderas'],
 true, true),

(NULL, 'Plancha lateral', 'Plancha lateral', 'Side Plank',
 'Trabajo de oblicuos isometrico',
 'core', ARRAY['obliques', 'abs'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/7/5/4375.gif',
 ARRAY['De lado, antebrazo en el suelo', 'Eleva las caderas', 'Cuerpo en linea recta', 'Mantén la posicion'],
 ARRAY['Caderas alineadas'],
 true, true),

(NULL, 'Elevacion de piernas colgado', 'Elevacion de piernas colgado', 'Hanging Leg Raise',
 'Ejercicio avanzado para abdomen bajo',
 'core', ARRAY['abs', 'hip_flexors'], ARRAY['pull_up_bar'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/3/1/4331.gif',
 ARRAY['Cuelgate de la barra', 'Eleva las piernas rectas hasta horizontal', 'Baja controladamente'],
 ARRAY['Evita el balanceo'],
 true, true),

(NULL, 'Elevacion de rodillas colgado', 'Elevacion de rodillas colgado', 'Hanging Knee Raise',
 'Version mas facil de elevacion de piernas',
 'core', ARRAY['abs', 'hip_flexors'], ARRAY['pull_up_bar'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/3/3/4333.gif',
 ARRAY['Cuelgate de la barra', 'Eleva las rodillas hacia el pecho', 'Baja con control'],
 ARRAY['Buen ejercicio inicial'],
 true, true),

(NULL, 'Russian twist', 'Giro ruso', 'Russian Twist',
 'Rotacion para oblicuos',
 'core', ARRAY['obliques', 'abs'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/5/9/4359.gif',
 ARRAY['Sentado, piernas elevadas', 'Rota el torso de lado a lado', 'Toca el suelo a cada lado'],
 ARRAY['Añade peso para mayor desafio'],
 true, true),

(NULL, 'Bicycle crunch', 'Crunch bicicleta', 'Bicycle Crunch',
 'Trabajo de oblicuos dinamico',
 'core', ARRAY['abs', 'obliques'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/1/9/4319.gif',
 ARRAY['Acostado, manos en la cabeza', 'Codo hacia rodilla opuesta', 'Alterna en movimiento de pedaleo'],
 ARRAY['Extiende bien la pierna'],
 true, true),

(NULL, 'Mountain climbers', 'Escaladores', 'Mountain Climbers',
 'Ejercicio cardio y core',
 'cardio', ARRAY['abs', 'hip_flexors'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/9/1/4391.gif',
 ARRAY['Posicion de plancha alta', 'Lleva rodillas al pecho alternadamente', 'Mantén ritmo rapido'],
 ARRAY['Mantén las caderas bajas'],
 true, true),

(NULL, 'Dead bug', 'Dead bug', 'Dead Bug',
 'Estabilizacion de core',
 'core', ARRAY['abs', 'lower_back'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/8/7/4387.gif',
 ARRAY['Acostado boca arriba', 'Brazos y piernas elevados', 'Extiende brazo y pierna opuestos', 'Alterna manteniendo espalda baja pegada'],
 ARRAY['No arquees la espalda'],
 true, true),

(NULL, 'Ab wheel rollout', 'Rueda abdominal', 'Ab Wheel Rollout',
 'Ejercicio avanzado de core',
 'core', ARRAY['abs', 'lower_back'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/3/0/5/4305.gif',
 ARRAY['Arrodillado con la rueda', 'Rueda hacia adelante extendiendo el cuerpo', 'Regresa contrayendo abdominales'],
 ARRAY['Empieza con rango corto'],
 true, true),

(NULL, 'Crunch en polea', 'Crunch en polea', 'Cable Crunch',
 'Crunch con resistencia',
 'core', ARRAY['abs'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/2/5/4325.gif',
 ARRAY['Arrodillado frente a polea alta', 'Cuerda detras de la cabeza', 'Flexiona el torso hacia abajo', 'Aprieta los abdominales'],
 ARRAY['No uses los brazos'],
 true, true),

(NULL, 'V-ups', 'V-ups', 'V-ups',
 'Ejercicio avanzado de abdomen',
 'core', ARRAY['abs', 'hip_flexors'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/3/6/7/4367.gif',
 ARRAY['Acostado con brazos extendidos', 'Eleva piernas y torso simultaneamente', 'Toca los pies con las manos', 'Baja con control'],
 ARRAY['Movimiento explosivo'],
 true, true),

(NULL, 'Crunch inverso', 'Crunch inverso', 'Reverse Crunch',
 'Enfasis en abdomen inferior',
 'core', ARRAY['abs'], ARRAY['bodyweight'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/1/5/4315.gif',
 ARRAY['Acostado con piernas elevadas', 'Eleva las caderas del suelo', 'Lleva rodillas al pecho', 'Baja controladamente'],
 ARRAY['No uses impulso'],
 true, true),

(NULL, 'Hollow body hold', 'Hollow body hold', 'Hollow Body Hold',
 'Posicion de gimnasia para core',
 'core', ARRAY['abs'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/3/8/1/4381.gif',
 ARRAY['Acostado boca arriba', 'Brazos y piernas extendidos y elevados', 'Espalda baja pegada al suelo', 'Mantén la posicion'],
 ARRAY['Forma de banana'],
 true, true),

(NULL, 'L-sit', 'L-sit', 'L-Sit',
 'Ejercicio isometrico avanzado',
 'core', ARRAY['abs', 'hip_flexors'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/3/9/7/4397.gif',
 ARRAY['Manos en paralelas o suelo', 'Eleva el cuerpo', 'Piernas extendidas horizontales', 'Mantén la posicion'],
 ARRAY['Requiere fuerza de triceps tambien'],
 true, true),

(NULL, 'Pallof press', 'Pallof press', 'Pallof Press',
 'Anti-rotacion de core',
 'core', ARRAY['abs', 'obliques'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/4/0/1/4401.gif',
 ARRAY['De pie lateral a la polea', 'Cable a la altura del pecho', 'Extiende los brazos resistiendo la rotacion', 'Regresa al pecho'],
 ARRAY['Excelente para estabilidad'],
 true, true),

(NULL, 'Wood chop', 'Wood chop', 'Cable Wood Chop',
 'Rotacion con resistencia',
 'core', ARRAY['obliques', 'abs'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/4/0/5/4405.gif',
 ARRAY['Polea alta en diagonal', 'Tira en diagonal hacia abajo', 'Rota el torso', 'Controla el regreso'],
 ARRAY['Movimiento de todo el cuerpo'],
 true, true),

(NULL, 'Crunch en maquina', 'Crunch en maquina', 'Machine Crunch',
 'Crunch guiado con resistencia',
 'core', ARRAY['abs'], ARRAY['machine'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/3/2/7/4327.gif',
 ARRAY['Ajusta el asiento', 'Agarra las manijas', 'Flexiona el torso hacia adelante'],
 ARRAY['Ideal para añadir peso progresivamente'],
 true, true),

(NULL, 'Dragon flag', 'Dragon flag', 'Dragon Flag',
 'Ejercicio extremadamente avanzado',
 'core', ARRAY['abs', 'lower_back'], ARRAY['bench'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/3/8/3/4383.gif',
 ARRAY['Acostado agarrando banco detras', 'Eleva todo el cuerpo recto', 'Baja manteniendo rigido', 'Solo hombros tocan'],
 ARRAY['Requiere gran fuerza de core'],
 true, true),

(NULL, 'Toes to bar', 'Toes to bar', 'Toes to Bar',
 'Ejercicio de CrossFit para core',
 'core', ARRAY['abs', 'hip_flexors'], ARRAY['pull_up_bar'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/3/3/5/4335.gif',
 ARRAY['Cuelgate de la barra', 'Eleva las piernas hasta tocar la barra', 'Baja con control', 'Puede usar kipping'],
 ARRAY['Fundamental en CrossFit'],
 true, true),

-- =============================================================================
-- EJERCICIOS DE CROSSFIT / FUNCTIONAL (25 exercises)
-- =============================================================================

(NULL, 'Burpee', 'Burpee', 'Burpee',
 'Ejercicio de cuerpo completo',
 'cardio', ARRAY['full_body'], ARRAY['bodyweight'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/1/0/7/4107.gif',
 ARRAY['De pie, baja a sentadilla', 'Manos al suelo, salta a plancha', 'Haz una flexion', 'Salta pies hacia manos', 'Salta con brazos arriba'],
 ARRAY['Mantén ritmo constante'],
 true, true),

(NULL, 'Thruster', 'Thruster', 'Thruster',
 'Sentadilla frontal a press',
 'compound', ARRAY['quadriceps', 'shoulders', 'glutes'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/4/1/5/2415.gif',
 ARRAY['Barra en posicion de sentadilla frontal', 'Baja en sentadilla', 'Sube explosivamente', 'Usa el impulso para presionar'],
 ARRAY['Movimiento fluido'],
 true, true),

(NULL, 'Clean', 'Clean', 'Power Clean',
 'Levantamiento olimpico',
 'olympic', ARRAY['full_body'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/0/0/5/2005.gif',
 ARRAY['Barra en el suelo', 'Primer tiron hasta rodillas', 'Segundo tiron explosivo', 'Recibe en posicion de sentadilla frontal'],
 ARRAY['Requiere tecnica precisa'],
 true, true),

(NULL, 'Snatch', 'Snatch', 'Snatch',
 'Levantamiento olimpico completo',
 'olympic', ARRAY['full_body'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/0/1/7/2017.gif',
 ARRAY['Agarre ancho en la barra', 'Tiron desde el suelo', 'Recibe con brazos extendidos overhead', 'En posicion de sentadilla profunda'],
 ARRAY['El mas tecnico de los levantamientos'],
 true, true),

(NULL, 'Clean and jerk', 'Clean and jerk', 'Clean and Jerk',
 'Combinacion de clean y jerk',
 'olympic', ARRAY['full_body'], ARRAY['barbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/0/0/9/2009.gif',
 ARRAY['Clean hasta los hombros', 'Dip y drive para el jerk', 'Recibe en split o power position'],
 ARRAY['Dos movimientos en uno'],
 true, true),

(NULL, 'Box jump', 'Box jump', 'Box Jump',
 'Salto pliometrico a caja',
 'plyometric', ARRAY['quadriceps', 'glutes', 'calves'], ARRAY['box'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/1/3/4513.gif',
 ARRAY['De pie frente a la caja', 'Flexiona y salta', 'Aterriza suavemente en la caja', 'Extiende completamente arriba'],
 ARRAY['Baja caminando, no saltando'],
 true, true),

(NULL, 'Wall ball', 'Wall ball', 'Wall Ball',
 'Sentadilla con lanzamiento de balon',
 'functional', ARRAY['quadriceps', 'shoulders', 'glutes'], ARRAY['medicine_ball'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/9/1/4591.gif',
 ARRAY['Balon medicinal frente al pecho', 'Baja en sentadilla', 'Sube y lanza el balon a objetivo', 'Atrapa y repite'],
 ARRAY['Objetivo tipicamente a 3m'],
 true, true),

(NULL, 'Kettlebell swing', 'Kettlebell swing', 'Kettlebell Swing',
 'Ejercicio de cadena posterior',
 'functional', ARRAY['glutes', 'hamstrings', 'lower_back'], ARRAY['kettlebell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/4/7/4547.gif',
 ARRAY['Kettlebell entre las piernas', 'Hip hinge hacia atras', 'Extension explosiva de caderas', 'Kettlebell sube a altura de ojos'],
 ARRAY['Poder de caderas, no brazos'],
 true, true),

(NULL, 'Turkish get-up', 'Turkish get-up', 'Turkish Get-up',
 'Levantamiento complejo desde el suelo',
 'functional', ARRAY['full_body'], ARRAY['kettlebell'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/5/5/5/4555.gif',
 ARRAY['Acostado con kettlebell en una mano', 'Serie de movimientos para ponerse de pie', 'Brazo extendido todo el tiempo', 'Regresa al suelo invirtiendo'],
 ARRAY['Aprende sin peso primero'],
 true, true),

(NULL, 'Muscle-up', 'Muscle-up', 'Muscle-up',
 'Dominada a fondo en barra',
 'gymnastics', ARRAY['back', 'chest', 'triceps'], ARRAY['pull_up_bar'],
 'advanced',
 'https://www.gymvisual.com/img/p/1/5/5/9/1559.gif',
 ARRAY['Dominada explosiva', 'Transicion sobre la barra', 'Fondo en la barra', 'Baja controladamente'],
 ARRAY['Requiere mucha fuerza y tecnica'],
 true, true),

(NULL, 'Double under', 'Double under', 'Double Under',
 'Salto de cuerda con doble giro',
 'cardio', ARRAY['calves', 'shoulders'], ARRAY['rope'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/1/7/3/4173.gif',
 ARRAY['Salto de cuerda normal', 'Salta mas alto', 'Gira la cuerda dos veces por salto', 'Mantén muñecas cerca del cuerpo'],
 ARRAY['Practica timing'],
 true, true),

(NULL, 'Rowing', 'Remo en maquina', 'Rowing Machine',
 'Cardio de cuerpo completo',
 'cardio', ARRAY['back', 'quadriceps', 'biceps'], ARRAY['rower'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/1/6/1/4161.gif',
 ARRAY['Empuja con las piernas primero', 'Luego tira con la espalda', 'Finalmente brazos', 'Regresa en orden inverso'],
 ARRAY['Secuencia: piernas, espalda, brazos'],
 true, true),

(NULL, 'Assault bike', 'Assault bike', 'Assault Bike',
 'Bicicleta de aire para cardio intenso',
 'cardio', ARRAY['quadriceps', 'glutes', 'shoulders'], ARRAY['bike'],
 'beginner',
 'https://www.gymvisual.com/img/p/4/1/5/7/4157.gif',
 ARRAY['Pedalea y empuja/tira los brazos', 'Resistencia aumenta con velocidad', 'Mantén ritmo constante'],
 ARRAY['Excelente para intervalos'],
 true, true),

(NULL, 'Sled push', 'Sled push', 'Sled Push',
 'Empuje de trineo',
 'functional', ARRAY['quadriceps', 'glutes', 'calves'], ARRAY['machine'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/7/8/5/4785.gif',
 ARRAY['Manos en las manijas altas o bajas', 'Inclinate hacia adelante', 'Empuja con pasos potentes', 'Mantén el core apretado'],
 ARRAY['Posicion baja = mas piernas'],
 true, true),

(NULL, 'Sled pull', 'Sled pull', 'Sled Pull',
 'Tiron de trineo',
 'functional', ARRAY['back', 'biceps', 'hamstrings'], ARRAY['machine'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/7/8/7/4787.gif',
 ARRAY['Agarra la cuerda o arnes', 'Camina hacia atras tirando', 'Mantén postura erguida'],
 ARRAY['Trabaja la cadena posterior'],
 true, true),

(NULL, 'Battle ropes', 'Battle ropes', 'Battle Ropes',
 'Cuerdas de batalla para cardio',
 'cardio', ARRAY['shoulders', 'abs', 'back'], ARRAY['rope'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/1/8/3/4183.gif',
 ARRAY['Agarra un extremo en cada mano', 'Crea ondas alternando brazos', 'Mantén las rodillas ligeramente flexionadas', 'Mueve desde los hombros'],
 ARRAY['Mantén ritmo constante'],
 true, true),

(NULL, 'Rope climb', 'Rope climb', 'Rope Climb',
 'Subir cuerda',
 'gymnastics', ARRAY['back', 'biceps', 'forearms'], ARRAY['rope'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/7/2/5/4725.gif',
 ARRAY['Agarra la cuerda arriba', 'Usa tecnica de pies (J-hook o S-wrap)', 'Sube mano sobre mano', 'Baja controladamente'],
 ARRAY['Aprende la tecnica de pies primero'],
 true, true),

(NULL, 'Handstand walk', 'Handstand walk', 'Handstand Walk',
 'Caminar en parada de manos',
 'gymnastics', ARRAY['shoulders', 'triceps', 'abs'], ARRAY['bodyweight'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/4/4/5/4445.gif',
 ARRAY['Parada de manos libre', 'Balancea el peso de lado a lado', 'Mueve las manos para caminar', 'Mantén el core muy apretado'],
 ARRAY['Practica contra la pared primero'],
 true, true),

(NULL, 'Kipping pull-up', 'Kipping pull-up', 'Kipping Pull-up',
 'Dominada con impulso de caderas',
 'gymnastics', ARRAY['back', 'biceps'], ARRAY['pull_up_bar'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/5/5/7/1557.gif',
 ARRAY['Crea movimiento de kip', 'Usa caderas para generar impulso', 'Tira cuando caderas van adelante', 'Empuja lejos en el descenso'],
 ARRAY['Aprende el kip primero'],
 true, true),

(NULL, 'Snatch grip deadlift', 'Peso muerto agarre snatch', 'Snatch Grip Deadlift',
 'Peso muerto con agarre ancho',
 'olympic', ARRAY['back', 'glutes', 'hamstrings'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/9/9/7/1997.gif',
 ARRAY['Agarre ancho como en snatch', 'Mayor rango de movimiento', 'Mantén espalda recta', 'Extiende caderas y rodillas'],
 ARRAY['Excelente para desarrollo de espalda'],
 true, true),

(NULL, 'Hang clean', 'Hang clean', 'Hang Clean',
 'Clean desde posicion colgante',
 'olympic', ARRAY['full_body'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/0/7/2007.gif',
 ARRAY['Barra colgando a la altura de rodillas', 'Extension explosiva de caderas', 'Recibe en posicion de sentadilla frontal'],
 ARRAY['Bueno para aprender el segundo tiron'],
 true, true),

(NULL, 'Push jerk', 'Push jerk', 'Push Jerk',
 'Jerk con recepcion en semi-sentadilla',
 'olympic', ARRAY['shoulders', 'triceps', 'quadriceps'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/1/5/2015.gif',
 ARRAY['Barra en los hombros', 'Dip y drive explosivo', 'Recibe en semi-sentadilla con brazos bloqueados', 'De pie para completar'],
 ARRAY['Mas facil que split jerk'],
 true, true),

(NULL, 'Goblet squat clean', 'Goblet squat clean', 'Goblet Squat Clean',
 'Clean con kettlebell a posicion goblet',
 'functional', ARRAY['quadriceps', 'glutes', 'biceps'], ARRAY['kettlebell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/4/9/4549.gif',
 ARRAY['Kettlebell entre los pies', 'Tiron y recepcion en posicion goblet', 'En sentadilla profunda'],
 ARRAY['Buena introduccion al clean'],
 true, true),

(NULL, 'Devil press', 'Devil press', 'Devil Press',
 'Burpee con snatch de mancuernas',
 'functional', ARRAY['full_body'], ARRAY['dumbbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/5/8/6/5/5865.gif',
 ARRAY['Burpee sosteniendo mancuernas', 'Al subir, snatch las mancuernas', 'Recibe overhead', 'Baja y repite'],
 ARRAY['Ejercicio muy demandante'],
 true, true),

(NULL, 'Manmakers', 'Manmakers', 'Manmakers',
 'Combinacion compleja con mancuernas',
 'functional', ARRAY['full_body'], ARRAY['dumbbell'],
 'advanced',
 'https://www.gymvisual.com/img/p/5/8/6/7/5867.gif',
 ARRAY['Burpee con remo en plancha', 'Clean las mancuernas', 'Thruster', 'Baja y repite'],
 ARRAY['Movimiento muy completo'],
 true, true),

-- =============================================================================
-- EJERCICIOS ADICIONALES VARIADOS (15 exercises)
-- =============================================================================

(NULL, 'Face pull con rotacion', 'Face pull con rotacion', 'Face Pull with External Rotation',
 'Version avanzada del face pull',
 'strength', ARRAY['shoulders', 'back'], ARRAY['cable'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/1/9/7/1197.gif',
 ARRAY['Tira hacia la cara', 'Rota externamente al final', 'Forma de doble biceps'],
 ARRAY['Excelente para salud del hombro'],
 true, true),

(NULL, 'Curl de muneca', 'Curl de muneca', 'Wrist Curl',
 'Fortalecimiento de antebrazos',
 'strength', ARRAY['forearms'], ARRAY['barbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/6/5/1165.gif',
 ARRAY['Antebrazos en las rodillas', 'Palmas hacia arriba', 'Flexiona las munecas hacia arriba'],
 ARRAY['Usa peso ligero'],
 true, true),

(NULL, 'Curl de muneca inverso', 'Curl de muneca inverso', 'Reverse Wrist Curl',
 'Fortalece extensores del antebrazo',
 'strength', ARRAY['forearms'], ARRAY['barbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/1/6/7/1167.gif',
 ARRAY['Palmas hacia abajo', 'Extiende las munecas hacia arriba', 'Control en el descenso'],
 ARRAY['Equilibra con curl normal'],
 true, true),

(NULL, 'Encogimiento de hombros en trampa', 'Encogimiento en trampa', 'Trap Bar Shrugs',
 'Encogimientos con barra trampa',
 'strength', ARRAY['back'], ARRAY['barbell'],
 'beginner',
 'https://www.gymvisual.com/img/p/1/6/8/7/1687.gif',
 ARRAY['Dentro de la barra trampa', 'Eleva los hombros', 'Mantén arriba brevemente'],
 ARRAY['Posicion mas natural que barra recta'],
 true, true),

(NULL, 'Press con kettlebell', 'Press con kettlebell', 'Kettlebell Press',
 'Press de hombro con kettlebell',
 'strength', ARRAY['shoulders', 'triceps'], ARRAY['kettlebell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/5/1/4551.gif',
 ARRAY['Kettlebell en rack position', 'Presiona hacia arriba', 'El peso cuelga detras de la mano'],
 ARRAY['Trabaja estabilizadores'],
 true, true),

(NULL, 'Clean con kettlebell', 'Clean con kettlebell', 'Kettlebell Clean',
 'Clean con kettlebell',
 'functional', ARRAY['full_body'], ARRAY['kettlebell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/5/4/5/4545.gif',
 ARRAY['Swing inicial', 'Tira con la cadera', 'Recibe en rack position', 'El KB rodea la mano'],
 ARRAY['No golpees el antebrazo'],
 true, true),

(NULL, 'Snatch con kettlebell', 'Snatch con kettlebell', 'Kettlebell Snatch',
 'Snatch con kettlebell',
 'functional', ARRAY['full_body'], ARRAY['kettlebell'],
 'advanced',
 'https://www.gymvisual.com/img/p/4/5/5/3/4553.gif',
 ARRAY['Swing con una mano', 'En vez de parar adelante, continua arriba', 'Recibe con brazo extendido', 'El KB rodea la mano arriba'],
 ARRAY['Tecnica de punch through'],
 true, true),

(NULL, 'Goblet reverse lunge', 'Zancada reversa goblet', 'Goblet Reverse Lunge',
 'Zancada reversa con peso goblet',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['dumbbell', 'kettlebell'],
 'beginner',
 'https://www.gymvisual.com/img/p/2/4/9/7/2497.gif',
 ARRAY['Peso frente al pecho', 'Paso hacia atras', 'Baja la rodilla', 'Regresa al inicio'],
 ARRAY['El peso ayuda con balance'],
 true, true),

(NULL, 'Renegade row', 'Renegade row', 'Renegade Row',
 'Remo en posicion de plancha',
 'compound', ARRAY['back', 'abs'], ARRAY['dumbbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/1/6/7/9/1679.gif',
 ARRAY['Plancha con manos en mancuernas', 'Rema un lado manteniendo plancha', 'Alterna lados', 'Resiste la rotacion'],
 ARRAY['Pies separados para estabilidad'],
 true, true),

(NULL, 'Single leg deadlift', 'Peso muerto a una pierna', 'Single Leg Deadlift',
 'Peso muerto unilateral',
 'strength', ARRAY['hamstrings', 'glutes'], ARRAY['dumbbell', 'kettlebell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/2/0/0/1/2001.gif',
 ARRAY['De pie en una pierna', 'Inclinate bajando el peso', 'Pierna libre se extiende atras', 'Regresa a posicion vertical'],
 ARRAY['Excelente para equilibrio'],
 true, true),

(NULL, 'Pendulum squat', 'Sentadilla pendulo', 'Pendulum Squat',
 'Sentadilla en maquina pendulo',
 'strength', ARRAY['quadriceps', 'glutes'], ARRAY['machine'],
 'intermediate',
 'https://www.gymvisual.com/img/p/5/8/6/3/5863.gif',
 ARRAY['Hombros en almohadillas', 'Pies en plataforma', 'Baja controladamente', 'Empuja hacia arriba'],
 ARRAY['Excelente para cuadriceps'],
 true, true),

(NULL, 'Copenhagen plank', 'Copenhagen plank', 'Copenhagen Plank',
 'Plancha lateral con enfasis en aductores',
 'core', ARRAY['obliques', 'hip_flexors'], ARRAY['bench'],
 'advanced',
 'https://www.gymvisual.com/img/p/5/8/7/3/5873.gif',
 ARRAY['Plancha lateral con pie superior en banco', 'Pierna inferior colgando', 'Eleva la pierna inferior al banco', 'Mantén caderas elevadas'],
 ARRAY['Muy demandante para aductores'],
 true, true),

(NULL, 'Seated good morning', 'Buenos dias sentado', 'Seated Good Morning',
 'Good morning desde posicion sentada',
 'strength', ARRAY['lower_back', 'hamstrings'], ARRAY['barbell'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/8/4/3/4843.gif',
 ARRAY['Sentado con barra en espalda', 'Inclinate hacia adelante', 'Mantén espalda recta', 'Regresa a vertical'],
 ARRAY['Asila mejor la espalda baja'],
 true, true),

(NULL, 'Glute ham raise', 'Glute ham raise', 'Glute Ham Raise',
 'Ejercicio avanzado para isquios y gluteos',
 'strength', ARRAY['hamstrings', 'glutes'], ARRAY['machine'],
 'advanced',
 'https://www.gymvisual.com/img/p/2/5/2/9/2529.gif',
 ARRAY['En maquina GHD', 'Baja el torso hacia adelante', 'Flexiona rodillas para subir', 'Usa gluteos e isquios'],
 ARRAY['Muy desafiante'],
 true, true),

(NULL, 'Reverse hyper', 'Reverse hyper', 'Reverse Hyper',
 'Extension inversa para espalda baja',
 'strength', ARRAY['lower_back', 'glutes', 'hamstrings'], ARRAY['machine'],
 'intermediate',
 'https://www.gymvisual.com/img/p/4/8/2/3/4823.gif',
 ARRAY['Torso en la maquina, piernas colgando', 'Eleva las piernas hacia atras', 'Aprieta gluteos arriba', 'Baja controladamente'],
 ARRAY['Excelente para espalda baja'],
 true, true);

-- =============================================================================
-- Add indexes for better query performance
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_exercises_category ON exercises(category) WHERE is_global = true;
CREATE INDEX IF NOT EXISTS idx_exercises_difficulty ON exercises(difficulty) WHERE is_global = true;
CREATE INDEX IF NOT EXISTS idx_exercises_muscle_groups ON exercises USING GIN(muscle_groups) WHERE is_global = true;
